#!/bin/bash
I_DIR="../input"
O_DIR="../output"
echo 'compiling'
echo '....'
g++ main.cpp -o justify.exe
echo '.'
echo '.'
echo '.'
echo 'executing flush left'
echo '.'
./justify.exe ../input/example.txt ../output/fl_out.txt 16 flush_left;echo '.'
echo '.'
echo '.'
echo 'executing flush right'
echo '.'
./justify.exe ../input/example.txt ../output/fr_out.txt 16 flush_right;echo '.'
echo '.'
echo '.'
echo 'executing full justify'
echo '.'
./justify.exe ../input/example.txt ../output/full_out.txt 16 full_justify;echo '.'
echo '.'
echo '.'
./justify.exe ../input/gettysburg_address.txt ../output/chris_is_a_grouch_gtsbrg_FL.txt 70 flush_left;echo '.'
echo '.'
echo '.'
echo 'executing flush right'
echo '.'
./justify.exe ../input/gettysburg_address.txt ../output/chris_is_a_grouch_gtsbrg_FR.txt 70 flush_right;echo '.'
echo '.'
echo '.'
echo 'executing full justify'
echo '.'
./justify.exe ../input/gettysburg_address.txt ../output/chris_is_a_grouch_gtsbrg_FJ.txt 70 full_justify;echo '.'
echo '.'
echo '.'
./justify.exe ../input/long_word.txt ../output/chris_is_a_grouch_Lword_FL.txt 15 flush_left;echo '.'
echo '.'
echo '.'
echo 'executing flush right'
echo '.'
./justify.exe ../input/long_word.txt ../output/chris_is_a_grouch_Lword_FR.txt 15 flush_right;echo '.'
echo '.'
echo '.'
echo 'executing full justify'
echo '.'
./justify.exe ../input/long_word.txt ../output/chris_is_a_grouch_Lword_FJ.txt 15 full_justify;echo '.'
echo '.'
echo '.'